### ISSUE TITLE
error opening pcap handle: sit0: That device is not up

### ISSUE THREAD

**Issue by paymini** [k8spacket/k8spacket#17]
I install on minikube 1.22.1
![image](https://user-images.githubusercontent.com/86401358/209915606-78a1c2d4-7dc8-4b38-bf28-d0f369bd86e4.png)

**Comment by k8spacket** [comment]
@paymini 
There is a possibility to customize a command to achieve network interfaces. See https://github.com/k8spacket/k8spacket-helm-chart/blob/master/charts/k8spacket/values.yaml#L71

I think in your case this command should be sth like this:
```
ip address | grep @ | grep veth | sed -E 's/.* (\w+)@.*/\1/' | tr '\n' ',' | sed 's/.$//'
```

You can create a custom helm values file f.e. custom-values.yaml with the content:
```
k8sPacket:
  tcp:
    listener:
      interfaces:
        command: "ip address | grep @ | grep veth | sed -E 's/.* (\\w+)@.*/\\1/' | tr '\\n' ',' | sed 's/.$//'"
```

And run the helm install command with the custom file path provided:
```
helm install k8spacket --namespace k8spacket k8spacket/k8spacket --create-namespace -f custom-values.yaml
```
