### ISSUE TITLE
Grafana TLS graph connections and certificates - blank

### ISSUE THREAD

**Issue by tlb1galaxy** [k8spacket/k8spacket#31]
## Issue

The Grafana graph to show TLS connections & certificates is blank and shows an error.

## Error messages

``` html
<html> <head><title>404 Not Found</title></head> <body> <center><h1>404 Not Found</h1></center> <hr><center>nginx/1.20.2</center> </body> </html> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page -->
```

```yaml
status:404
statusText:"Not Found"
data:Object
message:"<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.20.2</center>
</body>
</html>
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
"
error:"Not Found"
response:"<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.20.2</center>
</body>
</html>
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
"
config:Object
url:"api/datasources/proxy/1"
method:"GET"
headers:Object
retry:0
hideFromInspector:false
message:"<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.20.2</center>
</body>
</html>
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
"
```

## Duplicate Error
1.  ```helm install kube-prometheus prometheus-community/kube-prometheus-stack --v43.1.1```
2.  ```helm install -n k8spacket k8spacket/k8spacket --version 1.1.1```
3. ```helm upgrade kube-prometheus --v43.1.1 -f helm_grafana_patch_k8spacket_plugins.yaml```
4. Add k8spacket-prometheus-scrape-job.yaml to Prometheus scrape jobs
5. ```kubectl apply -n monitoring -R -f ~/k8s/k8spacket/v1.1.1/git/k8spacket/dashboards/```

### helm_grafana_patch_k8spacket_plugins.yaml

```yaml
grafana:
  env:
    GF_INSTALL_PLUGINS: hamedkarbasi93-nodegraphapi-datasource,marcusolsson-json-datasource,marcusolsson-dynamictext-panel
  datasources:
    nodegraphapi-plugin-datasource.yaml:
      apiVersion: 1
      datasources:
        - name: "Node Graph API"
          jsonData:
            url: "http://k8spacket.k8spacket.svc.cluster.local:8080/nodegraph"
          access: "proxy"
          basicAuth: false
          isDefault: false
          readOnly: false
          type: "hamedkarbasi93-nodegraphapi-datasource"
          typeLogoUrl: "public/plugins/hamedkarbasi93-nodegraphapi-datasource/img/logo.svg"
          typeName: "node-graph-plugin"
          orgId: 1
          version: 1
    marcusolsson-json-datasource.yaml:
      apiVersion: 1
      datasources:
        - name: "JSON API"
          url: "http://k8spacket.k8spacket.svc.cluster.local:8080/tlsparser/api/data"
          access: "proxy"
          basicAuth: false
          isDefault: false
          readOnly: false
          type: "marcusolsson-json-datasource"
          typeLogoUrl: "public/plugins/marcusolsson-json-datasource/img/logo.svg"
          typeName: "json-api-plugin"
          orgId: 1
          version: 1
```

## Environment

- kubeadm
```bash
kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-15T14:22:29Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-15T14:15:38Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
``` 

### Graph page JSON panel
```json
{
  "id": 4,
  "gridPos": {
    "h": 9,
    "w": 24,
    "x": 0,
    "y": 0
  },
  "type": "table",
  "title": "TLS Connections",
  "datasource": {
    "type": "marcusolsson-json-datasource",
    "uid": "${datasource}"
  },
  "pluginVersion": "9.3.1",
  "fieldConfig": {
    "defaults": {
      "custom": {
        "align": "center",
        "displayMode": "auto",
        "inspect": false,
        "filterable": true,
        "minWidth": 50
      },
      "mappings": [],
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "color": "green",
            "value": null
          },
          {
            "color": "red",
            "value": 80
          }
        ]
      },
      "color": {
        "mode": "thresholds"
      },
      "links": [
        {
          "title": "Show details",
          "url": "/d/_WjaqJt4k/k8spacket-tls-connections-and-certificates?var-id=${__data.fields[\"id\"]}"
        }
      ]
    },
    "overrides": [
      {
        "matcher": {
          "id": "byName",
          "options": "id"
        },
        "properties": [
          {
            "id": "custom.hidden",
            "value": true
          }
        ]
      }
    ]
  },
  "options": {
    "showHeader": true,
    "footer": {
      "show": false,
      "reducer": [
        "sum"
      ],
      "fields": "",
      "enablePagination": false
    },
    "sortBy": [
      {
        "desc": true,
        "displayName": "usedTLSVersion"
      }
    ]
  },
  "targets": [
    {
      "cacheDurationSeconds": 300,
      "datasource": {
        "type": "marcusolsson-json-datasource",
        "uid": "${datasource}"
      },
      "fields": [
        {
          "jsonPath": "$[*].src",
          "name": "src"
        },
        {
          "jsonPath": "$[*].srcName",
          "language": "jsonpath",
          "name": "srcName"
        },
        {
          "jsonPath": "$[*].srcNamespace",
          "language": "jsonpath",
          "name": "srcNamespace"
        },
        {
          "jsonPath": "$[*].dst",
          "language": "jsonpath",
          "name": "dst"
        },
        {
          "jsonPath": "$[*].dstName",
          "language": "jsonpath",
          "name": "dstName"
        },
        {
          "jsonPath": "$[*].dstPort",
          "language": "jsonpath",
          "name": "dstPort"
        },
        {
          "jsonPath": "$[*].domain",
          "language": "jsonpath",
          "name": "domain"
        },
        {
          "jsonPath": "$[*].usedTLSVersion",
          "language": "jsonpath",
          "name": "usedTLSVersion"
        },
        {
          "jsonPath": "$[*].usedCipherSuite",
          "language": "jsonpath",
          "name": "usedCipherSuite"
        },
        {
          "jsonPath": "$[*].id",
          "language": "jsonpath",
          "name": "id"
        }
      ],
      "method": "GET",
      "queryParams": "",
      "refId": "A",
      "urlPath": ""
    }
  ]
}
```

**Comment by k8spacket** [comment]
Hi @tlb1galaxy 
Thanks for the feedback.

The problem was connected with a trailing slash when calling the TLS connections list on `/tls-parser/api/data/`. 
I fixed it in version 1.1.2 of the plugin.

To use it, update the repo and then upgrade the chart:
```
helm repo update k8spacket
helm upgrade --install k8spacket --namespace k8spacket k8spacket/k8spacket
```

**Comment by tlb1galaxy** [comment]
Hello,
I updated the repo and chart installation.  The Grafana TLS chart is still empty.

```bash
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
k8spacket       k8spacket       3               2023-03-13 12:41:47.520327375 +0000 UTC deployed        k8spacket-1.1.2 1.1.1
```

Does the Grafana plugin patch need to change too?  Does the URL need to have the trailing slash or you matched the backend to match?

```yaml
marcusolsson-json-datasource.yaml:
      apiVersion: 1
      datasources:
        - name: "JSON API"
          url: "http://k8spacket.k8spacket.svc.cluster.local:8080/tlsparser/api/data"
```

**Comment by k8spacket** [comment]
Hi @tlb1galaxy 
Is it possible it is empty because there weren't any TLS connections inside your cluster yet?
Maybe you need to wait or try to call some https site from the container inside the cluster by the curl command?

You don't need to change anything in the dashboard definition.

**Comment by tlb1galaxy** [comment]
This is more of a question for my clarification.

When I look at the "TLS Metrics" graph, it has 3 data streams (currently)  
I would assume the "TLS connections & certificates" would also show data based on the items found in the Metrics graph.  

**TLS Metrics graph**:  
Does this map show any/all TLS requests from any pod or only intra-pod TLS connections?

I also spun up a pod in a NS and executed a few curls to various HTTPS sites.  I do not see these requests in either graph.
So assuming this is showing only successful mTLS intra-pod connections?

**Comment by k8spacket** [comment]
"TLS Metrics" is based on Prometheus metrics (stored in Prometheus), so it will show connections even after the reinstallation of k8spacket.
"TLS connections & certificates" is based on local data stored in k8spacket containers, so after reinstallation, the previous connections disappear.

"TLS Metrics" should show the same connections as "TLS connections & certificates", but only, when these connections appeared after the last reinstallation of k8spacket.

Both dashboards should show connections to the outside and between pods, but remember that the container needs to be running for more than 10 seconds to be visible for k8spacket listeners (https://github.com/k8spacket/k8spacket-helm-chart/blob/master/charts/k8spacket/values.yaml#L72)

Is this new pod visible on the `k8spacket-node-graph` panel? If the answer is yes, your hits by curl command should be visible on "TLS connections & certificates"

**Comment by tlb1galaxy** [comment]
Thanks for the clarification on the data.

I will play and verify with that later today.  I assume for me, I have no new TLS connections made for the graph to populate (as you mentioned before).

**Comment by k8spacket** [comment]
@tlb1galaxy 
Do you have another JSON API data source declared in Grafana?

<img width="263" alt="image" src="https://user-images.githubusercontent.com/95187481/225021761-be42d47b-eb12-45c3-8f47-36587ff7ada1.png">

Maybe this dashboard is trying to use the wrong data source 🤔 

Check it in this way:
- on the dashboard "TLS connections & certificates" click the button at the right top ⚙️ 
- go to "Variables" and choose "datasource"
- change the field "Hide" to empty & click "Apply"
- back to dashboard ◀️ 

<img width="400" alt="image" src="https://user-images.githubusercontent.com/95187481/225023330-054fbdc3-bc65-4e85-b1b7-b1c8f9f3e936.png">

What do you see?

**Comment by tlb1galaxy** [comment]
So I copied the "TLS connections & cert" chart to a new chart (as since these were applied via kubectl, it would not allow me to modify.

I also could not change the datasource to nothing (without deleting and recreating):  
- This brings up empty charts and when I refresh page, it errors out with no datasource found [assuming no default datasource is found]

![brave_rD5jcVXlTV](https://user-images.githubusercontent.com/77345094/225069364-9f00f9be-a108-418a-8258-818c72d76057.png)

**Comment by tlb1galaxy** [comment]
I deployed a pod in the k8spacket NS and ran a curl command to verify the JSON API URL (http://k8spacket.k8spacket.svc.cluster.local:8080/tlsparser/api/data)

```bash
# curl -vv http://k8spacket.k8spacket.svc.cluster.local:8080/tlsparser/api/data
*   Trying 172.16.24.51:8080...
* Connected to k8spacket.k8spacket.svc.cluster.local (172.16.24.51) port 8080 (#0)
> GET /tlsparser/api/data HTTP/1.1
> Host: k8spacket.k8spacket.svc.cluster.local:8080
> User-Agent: curl/7.81.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 301 Moved Permanently
< Content-Type: text/html; charset=utf-8
< Location: /tlsparser/api/data/
< Date: Tue, 14 Mar 2023 16:24:06 GMT
< Content-Length: 55
<
<a href="/tlsparser/api/data/">Moved Permanently</a>.

* Connection #0 to host k8spacket.k8spacket.svc.cluster.local left intact
```

When to go to ```curl -vv http://k8spacket.k8spacket.svc.cluster.local:8080/tlsparser/api/data/``` I actually get a full dump of data.

I am no Grafana expert (maybe a newbie at best) but seems the datasource URL might be missing the trailing '/'

**Comment by k8spacket** [comment]
@tlb1galaxy 
That was changed exactly in the last plugin version. The new version is v1.1.2, see: https://github.com/k8spacket/k8spacket-helm-chart/blob/master/charts/k8spacket/values.yaml#L56

You have the helm chart updated I see it here https://github.com/k8spacket/k8spacket/issues/31#issuecomment-1466135681
But did you use custom values.yaml file with the previous plugin's version? It looks like there is still a previous version installed.

You can check it with the command:
```
kubectl -n k8spacket describe pod <<k8spacket-pod-name>> | grep "K8S_PACKET_AVAILABLE_PLUGINS:"
```
You will get an answer with installed versions:
```
K8S_PACKET_AVAILABLE_PLUGINS:  https://github.com/k8spacket/plugins/releases/download/v1.1.2/nodegraph-$(arch).so,https://github.com/k8spacket/plugins/releases/download/v1.1.2/tls-parser-$(arch).so
```

**Comment by tlb1galaxy** [comment]
I think that is coming from the patch to Grafana:
```yaml
--- # ./helm_grafana_patch_k8spacket_plugins.yaml
grafana:
  env:
    GF_INSTALL_PLUGINS: hamedkarbasi93-nodegraphapi-datasource,marcusolsson-json-datasource,marcusolsson-dynamictext-panel
  datasources:
    nodegraphapi-plugin-datasource.yaml:
      apiVersion: 1
      datasources:
        - name: "Node Graph API"
          jsonData:
            url: "http://k8spacket.k8spacket.svc.cluster.local:8080/nodegraph"
          access: "proxy"
          basicAuth: false
          isDefault: false
          readOnly: false
          type: "hamedkarbasi93-nodegraphapi-datasource"
          typeLogoUrl: "public/plugins/hamedkarbasi93-nodegraphapi-datasource/img/logo.svg"
          typeName: "node-graph-plugin"
          orgId: 1
          version: 1
    marcusolsson-json-datasource.yaml:
      apiVersion: 1
      datasources:
        - name: "JSON API"
          url: "http://k8spacket.k8spacket.svc.cluster.local:8080/tlsparser/api/data"
          access: "proxy"
          basicAuth: false
          isDefault: false
          readOnly: false
          type: "marcusolsson-json-datasource"
          typeLogoUrl: "public/plugins/marcusolsson-json-datasource/img/logo.svg"
          typeName: "json-api-plugin"
          orgId: 1
          version: 1
...
```

This patch is missing the trailing '/' on the JSON API datasource.
So now I am confused:
- Should the trailing '/' be there for the URL or not?
    - assuming yes
```url: "http://k8spacket.k8spacket.svc.cluster.local:8080/tlsparser/api/data/"```

I can re-patch my Grafana deployment later to confirm
