### ISSUE TITLE
Not able to connect to Grafana, and getting 404 page not found in k8spacket though service

### ISSUE THREAD

**Issue by manojbamboobox** [k8spacket/k8spacket#43]
After completion of the command, I ran these below command as given
export NODE_PORT=$(kubectl get --namespace k8spacket -o jsonpath="{.spec.ports[0].nodePort}" services k8spacket)
export NODE_IP=$(kubectl get nodes --namespace k8spacket -o jsonpath="{.items[0].status.addresses[0].address}")
echo http://$NODE_IP:$NODE_PORT

Where I'm not getting port number.
When I tried to access through Grafana its showing no data found.
When I tried to access the service using port-forward using k8spacket its showing 404 page not found.
I'm receiving data in pods logs.

**Comment by k8spacket** [comment]
Hi @manojbamboobox 

This text after helm installation is more like general, default information. Don't trust them. 
But it's good feedback for me. It should be removed. Thanks.

A few things to check. Share results please:

Logs:
```
kubectl -n k8spacket logs <k8spacket-pod-name>
```

Describe pod:
```
kubectl -n k8spacket describe pod <k8spacket-pod-name>
```

Some questions:

Have you added additional job scraping to your Prometheus definition?
```
    - job_name: "k8spacket-metrics"
      metrics_path: /metrics
      scrape_interval: 25s
      static_configs:
      - targets: [k8spacket.k8spacket.svc.cluster.local:8080]
```
