### ISSUE TITLE
Node graph dashboard doesn't work out of the box

### ISSUE THREAD

**Issue by MattiasGees** [k8spacket/k8spacket#52]
> Caveat: I am not sure if this is k8spacket or a Grafana issue

I tried installing k8spacket to test it out. I currently have a cluster running the kube-prometheus-stack, which works fine and runs on the latest Helm chart version (58.0.0).  I installed the Helm chart for the K8spacket, which also works fine. Modified my `values.yaml` of the kube-prometheus-stack as follows:

```yaml
grafana:
  env:
    GF_INSTALL_PLUGINS: hamedkarbasi93-nodegraphapi-datasource,marcusolsson-json-datasource,marcusolsson-dynamictext-panel
  deploymentStrategy:
    type: Recreate
  additionalDataSources:
  - name: "Node Graph API"
    jsonData:
      url: "http://k8spacket.k8spacket.svc.cluster.local:8080/nodegraph"
    access: "proxy"
    basicAuth: false
    isDefault: false
    readOnly: false
    type: "hamedkarbasi93-nodegraphapi-datasource"
    typeLogoUrl: "public/plugins/hamedkarbasi93-nodegraphapi-datasource/img/logo.svg"
    typeName: "node-graph-plugin"
    orgId: 1
    version: 1
  - name: "JSON API"
    url: "http://k8spacket.k8spacket.svc.cluster.local:8080/tlsparser/api/data"
    access: "proxy"
    basicAuth: false
    isDefault: false
    readOnly: false
    type: "marcusolsson-json-datasource"
    typeLogoUrl: "public/plugins/marcusolsson-json-datasource/img/logo.svg"
    typeName: "json-api-plugin"
    orgId: 1
    version: 1
  sidecar:
    dashboards:
      searchNamespace: ALL
      provider:
        foldersFromFilesStructure: true

prometheus:
  prometheusSpec:
    retention: 14d
    logLevel: warn
    serviceMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    additionalScrapeConfigs:
    - job_name: "k8spacket-metrics"
      metrics_path: /metrics
      scrape_interval: 25s
      static_configs:
      - targets: [k8spacket.k8spacket.svc.cluster.local:8080]
```

So far, so good; I can see the data sources in Grafana and the `test` clear in the UI. I deployed my Grafana dashboards (`  kubectl -n $GRAFANA_NS apply --recursive -f ./dashboards` and I can see those also appear in Grafana. When I go to the node graph dashboard, I get the following

<img width="2557" alt="Screenshot 2024-04-09 at 16 06 45" src="https://github.com/k8spacket/k8spacket/assets/2216724/95fe9587-6978-4349-b3d4-721ee2c51fed">

When I edit the dashboard, select the datasource and add the query again, it starts to work.

<img width="2552" alt="Screenshot 2024-04-09 at 16 08 19" src="https://github.com/k8spacket/k8spacket/assets/2216724/97d361dd-ecaf-4171-b4fe-b4d2fe69da7d">

I exported that working dashboard and couldn't really see a difference between the export and the original. The exported yaml is:

```yaml
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "grafana",
          "uid": "-- Grafana --"
        },
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": 2529,
  "links": [],
  "liveNow": false,
  "panels": [
    {
      "datasource": {
        "type": "hamedkarbasi93-nodegraphapi-datasource",
        "uid": "PC93AC6A0E760905D"
      },
      "gridPos": {
        "h": 31,
        "w": 24,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "options": {
        "edges": {},
        "nodes": {}
      },
      "targets": [
        {
          "datasource": {
            "type": "hamedkarbasi93-nodegraphapi-datasource",
            "uid": "PC93AC6A0E760905D"
          },
          "queryText": "namespace=$namespace&include=$include&exclude=$exclude&stats-type=$statstype&from=${__from}&to=${__to}",
          "refId": "A"
        }
      ],
      "title": "Node graph",
      "type": "nodeGraph"
    }
  ],
  "refresh": "",
  "schemaVersion": 39,
  "tags": [
    "k8spacket"
  ],
  "templating": {
    "list": [
      {
        "current": {
          "selected": false,
          "text": "connection",
          "value": "connection"
        },
        "hide": 0,
        "includeAll": false,
        "label": "graph mode",
        "multi": false,
        "name": "statstype",
        "options": [
          {
            "selected": true,
            "text": "connection",
            "value": "connection"
          },
          {
            "selected": false,
            "text": "bytes",
            "value": "bytes"
          },
          {
            "selected": false,
            "text": "duration",
            "value": "duration"
          }
        ],
        "query": "connection,bytes,duration",
        "queryValue": "",
        "skipUrlSync": false,
        "type": "custom"
      },
      {
        "current": {
          "selected": false,
          "text": "",
          "value": ""
        },
        "description": "",
        "hide": 0,
        "label": "namespace (regexp)",
        "name": "namespace",
        "options": [
          {
            "selected": true,
            "text": "",
            "value": ""
          }
        ],
        "query": "",
        "skipUrlSync": false,
        "type": "textbox"
      },
      {
        "current": {
          "selected": false,
          "text": "",
          "value": ""
        },
        "hide": 0,
        "label": "include name (regexp)",
        "name": "include",
        "options": [
          {
            "selected": true,
            "text": "",
            "value": ""
          }
        ],
        "query": "",
        "skipUrlSync": false,
        "type": "textbox"
      },
      {
        "current": {
          "selected": false,
          "text": "",
          "value": ""
        },
        "hide": 0,
        "label": "exclude name (regexp)",
        "name": "exclude",
        "options": [
          {
            "selected": true,
            "text": "",
            "value": ""
          }
        ],
        "query": "",
        "skipUrlSync": false,
        "type": "textbox"
      },
      {
        "current": {
          "selected": false,
          "text": "Node Graph API",
          "value": "PC93AC6A0E760905D"
        },
        "hide": 2,
        "includeAll": false,
        "multi": false,
        "name": "datasource",
        "options": [],
        "query": "hamedkarbasi93-nodegraphapi-datasource",
        "queryValue": "",
        "refresh": 1,
        "regex": "",
        "skipUrlSync": false,
        "type": "datasource"
      }
    ]
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "k8spacket - node graph",
  "uid": "fdad1ee1-a619-493d-b0ff-2ca2682fdc57",
  "version": 1,
  "weekStart": ""
}
```

My hunch is that it automatically falls back to the default data source, which, in my case, is the Prometheus one. I am not 100% sure how to set the correct one.
