### ISSUE TITLE
Full grafana example 

### ISSUE THREAD

**Issue by OteemoSanjay** [k8spacket/k8spacket#54]
hi

Do you have a full grafana config file with the scrape_config.
At the moment the documentation doens seem to work on latest grafana (10.x) 

rgds sanj

**Comment by k8spacket** [comment]
Hi @OteemoSanjay 

You can check it on killercoda scenario: https://killercoda.com/k8spacket/scenario/k8spacket
and see the file by command:
```
cat promop-values.yaml
```

Additionally, I share important content here: 
```
...
grafana:
  env:
    GF_INSTALL_PLUGINS: hamedkarbasi93-nodegraphapi-datasource,marcusolsson-json-datasource,marcusolsson-dynamictext-panel
  datasources:
    nodegraphapi-plugin-datasource.yaml:
      apiVersion: 1
      datasources:
        - name: "Node Graph API"
          jsonData:
            url: "http://k8spacket.k8spacket.svc.cluster.local:8080/nodegraph"
          access: "proxy"
          basicAuth: false
          isDefault: false
          readOnly: false
          type: "hamedkarbasi93-nodegraphapi-datasource"
          typeLogoUrl: "public/plugins/hamedkarbasi93-nodegraphapi-datasource/img/logo.svg"
          typeName: "node-graph-plugin"
          orgId: 1
          version: 1
    marcusolsson-json-datasource.yaml:
      apiVersion: 1
      datasources:
        - name: "JSON API"
          url: "http://k8spacket.k8spacket.svc.cluster.local:8080/tlsparser/api/data"
          access: "proxy"
          basicAuth: false
          isDefault: false
          readOnly: false
          type: "marcusolsson-json-datasource"
          typeLogoUrl: "public/plugins/marcusolsson-json-datasource/img/logo.svg"
          typeName: "json-api-plugin"
          orgId: 1
          version: 1
...
prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: "k8spacket-metrics"
        metrics_path: /metrics
        scrape_interval: 25s
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - source_labels: [ __address__ ]
            action: replace
            regex: ([^:]+):.*
            replacement: $1:6676
            target_label: __address__
```

In the documentation, there is a service target and it should work as well:
```
    - job_name: "k8spacket-metrics"
      metrics_path: /metrics
      scrape_interval: 25s
      static_configs:
      - targets: [k8spacket.k8spacket.svc.cluster.local:8080]
```

Could you describe what exactly doesn't work on the latest grafana 10.x ?
