### ISSUE TITLE
The "ns" label contains an only one Namespace in Prometheus

### ISSUE THREAD

**Issue by setevoy2** [k8spacket/k8spacket#58]
Looks very weird...

I have installed `k8spacket` from the Helm chart with the following values:

```
tolerations: 
  - effect: NoSchedule
    operator: Exists
k8sPacket:
  volumes:
    tracingPath: '/sys/kernel/debug/tracing'
```

Next, I have scrape config in my Prometheus (actually, VicrotiaMetrcis, but no differece):

```
        - job_name: "k8spacket-metrics"
          metrics_path: /metrics
          scrape_interval: 25s
          static_configs:
          - targets: [k8spacket.k8spacket.svc.cluster.local:8080]
```

Now, in the Prometheus/VictoriaMetrics/Grafana I can see the only `ops-monitoring-ns` Namespace - the NS, where VictoriaMetrics/Grafana are running:

![image](https://github.com/k8spacket/k8spacket/assets/7965314/29c877d5-ca7e-41a3-ac5a-50e8bce0afb0)

But if I run `kk -n k8spacket port-forward svc/k8spacket 8080` and then check with `curl` - I can see all the Namespaces:

```
$ curl -s localhost:8080/metrics | grep k8s
...
k8s_packet_tls_record{cipher_suite="TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",domain="events.launchdarkly.com",dst="54.234.239.85",dst_name="Amazon Technologies Inc.",dst_port="443",ns="prod-backend-api-ns",src="10.0.38.180",src_name="pod.backend-celery-workers-deployment-8498b7c98d-5dvzb",tls_version="TLS 1.2"} 1
```

Here, I have the `ns="prod-backend-api-ns"`.
Why are they missing in VictoriaMetrics/Grafana?

I have other scrape configs, and everything is OK there.
