### ISSUE TITLE
No Node graph visible / available

### ISSUE THREAD

**Issue by Jeansen** [k8spacket/k8spacket#63]
I've installed version 2.0.4 of k8spacket as described in the README.

Regarding metrics, everything works, including the 'metrics-only' dashboards.

Dashboards that do not work for me are
- k8spacket-tls-connections-and-certificates
- k8spacket-node-graph
- k8spacket-tls-certificate-expiration

For the `k8spacket-tls-connections-and-certificates`, I also had to install the missing pluing `marcusolsson-dynamictext-panel`.

In the `Node Graph API` DataSource I see that there is no URL provided for the API app and I could not figure out so far what to put in there. So I guess that is, what is missing. But I cannot see that k8spacket exposes any API. There is only the `/metrics` endpoint.

With respect to `k8spacket-tls-certificate-expiration` the query seems invalid. There are selections by `domain`, instead of `namespace`. At least, I cannot see any domain label anywhere in the scrape data ...

My Grafana ist a recent Helm installation from https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack

**Comment by k8spacket** [comment]
Hi @Jeansen 

You can check the full configuration and interactive dashboards with killercoda scenario here: https://killercoda.com/k8spacket/scenario/k8spacket (repo https://github.com/k8spacket/killercoda/blob/master/k8spacket)

The additional configuration to helm values looks as below:
```
...
grafana:
  env:
    GF_INSTALL_PLUGINS: hamedkarbasi93-nodegraphapi-datasource,marcusolsson-json-datasource,marcusolsson-dynamictext-panel
  datasources:
    nodegraphapi-plugin-datasource.yaml:
      apiVersion: 1
      datasources:
        - name: "Node Graph API"
          jsonData:
            url: "http://k8spacket.k8spacket.svc.cluster.local:8080/nodegraph"
          access: "proxy"
          basicAuth: false
          isDefault: false
          readOnly: false
          type: "hamedkarbasi93-nodegraphapi-datasource"
          typeLogoUrl: "public/plugins/hamedkarbasi93-nodegraphapi-datasource/img/logo.svg"
          typeName: "node-graph-plugin"
          orgId: 1
          version: 1
    marcusolsson-json-datasource.yaml:
      apiVersion: 1
      datasources:
        - name: "JSON API"
          url: "http://k8spacket.k8spacket.svc.cluster.local:8080/tlsparser/api/data"
          access: "proxy"
          basicAuth: false
          isDefault: false
          readOnly: false
          type: "marcusolsson-json-datasource"
          typeLogoUrl: "public/plugins/marcusolsson-json-datasource/img/logo.svg"
          typeName: "json-api-plugin"
          orgId: 1
          version: 1
...
prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: "k8spacket-metrics"
        metrics_path: /metrics
        scrape_interval: 25s
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - source_labels: [ __address__ ]
            action: replace
            regex: ([^:]+):.*
            replacement: $1:6676
            target_label: __address__
```

The Grafana stack was installed with the command:
```
helm install promop --namespace monitoring prometheus-community/kube-prometheus-stack --create-namespace -f ./promop-values.yaml
```
See the script in repo https://github.com/k8spacket/killercoda/blob/master/k8spacket/background.sh

Regarding `k8spacket-tls-certificate-expiration`, this query is based on metric `k8s_packet_tls_cert_expiry`. The structure of it looks as follows:
```
k8s_packet_tls_cert_expiry{dst="52.58.254.253",dst_port="443",instance="node01",job="k8spacket-metrics",domain="letsencrypt.org"}           1725815545000
```
the field `domain` is a DNS called from one of the pods by TLS, and the value is the certificate's expiration time.
